//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public int id { get; set; }
        public int idItem { get; set; }
        public int count { get; set; }
        public decimal cost { get; set; }
        public int idStock { get; set; }
        public System.DateTime dateCount { get; set; }
    
        public virtual item item { get; set; }
        public virtual stock stock { get; set; }
    }
}
