//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAssistant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class orderAssistantEntities : DbContext
    {
        public orderAssistantEntities()
            : base("name=orderAssistantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachments { get; set; }
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<box> boxes { get; set; }
        public virtual DbSet<brend> brends { get; set; }
        public virtual DbSet<competitorsInternet> competitorsInternets { get; set; }
        public virtual DbSet<documentsTraffic> documentsTraffics { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<manufacturer> manufacturers { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<price> prices { get; set; }
        public virtual DbSet<pricesInternet> pricesInternets { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supply> supplies { get; set; }
    }
}
