//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        public int id { get; set; }
        public int idBox { get; set; }
        public int idItem { get; set; }
        public int count { get; set; }
        public decimal netWeight { get; set; }
        public decimal grossWeight { get; set; }
        public decimal netVolume { get; set; }
        public decimal grossVolume { get; set; }
    
        public virtual box box { get; set; }
        public virtual item item { get; set; }
    }
}
