//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public int id { get; set; }
        public decimal price1 { get; set; }
        public int idItem { get; set; }
        public int idSupplier { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
